FROM python:3
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY ./AMQPmessageclient.py .
COPY ./models.py .
COPY ./settings.py .
CMD [ "python", "./AMQPmessageclient.py"]